title: Ariane Carvajal Candia
description: Memorista de Ingeniería Civil Informática de la Universidad Tecnica Federico Santa María. Entusiasta de la interacción entre sociedad
y tecnología, con conocimientos en
captación y análisis de requerimientos.
Capaz de evaluar la viabilidad de soluciones
para asegurar que cumplan con las
necesidades y expectativas de las personas
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman